### ISSUE TITLE
Prevention of Duplicate Emails Not Working Properly

### ISSUE THREAD

**Issue by techangela1** [daveh/php-signup-login#12]
Hello,

Everything works fine except for the prevention of duplicate emails.  It appears that there is an error in the process-signup.php.  The code was copied directly from the source provided.  Perhaps, I inadvertently added or omitted a character.

**ERROR RECEIVED when a duplicate email was added for a new user:**

Fatal error: Uncaught mysqli_sql_exception: Duplicate entry 'hal@mail.com' for key 'email' in C:\xampp\htdocs\php-signup-login-main\process-signup.php:45 Stack trace: #0 C:\xampp\htdocs\php-signup-login-main\process-signup.php(45): mysqli_stmt->execute() #1 {main} thrown in C:\xampp\htdocs\php-signup-login-main\process-signup.php on line 45

This is the code for http://localhost/php-signup-login-main/process-signup.php:

<?php

if (empty($_POST["name"])) {
    die("Name is required");
}

if ( ! filter_var($_POST["email"], FILTER_VALIDATE_EMAIL)) {
    die("Valid email is required");
}

if (strlen($_POST["password"]) < 8) {
    die("Password must be at least 8 characters");
}

if ( ! preg_match("/[a-z]/i", $_POST["password"])) {
    die("Password must contain at least one letter");
}

if ( ! preg_match("/[0-9]/", $_POST["password"])) {
    die("Password must contain at least one number");
}

if ($_POST["password"] !== $_POST["password_confirmation"]) {
    die("Passwords must match");
}

$password_hash = password_hash($_POST["password"], PASSWORD_DEFAULT);

$mysqli = require __DIR__ . "/database.php";

$sql = "INSERT INTO user (name, email, password_hash)
        VALUES (?, ?, ?)";
        
$stmt = $mysqli->stmt_init();

if ( ! $stmt->prepare($sql)) {
    die("SQL error: " . $mysqli->error);
}

$stmt->bind_param("sss",
                  $_POST["name"],
                  $_POST["email"],
                  $password_hash);
                  
if ($stmt->execute()) {

    header("Location: signup-success.html");
    exit;
    
} else {
    
    if ($mysqli->errno === 1062) {
        die("email already taken");
    } else {
        die($mysqli->error . " " . $mysqli->errno);
    }
}

**Comment by techangela1** [comment]
Prevention of Duplicate Emails Not Working Properly  #12 

As stated previously, the login system works fine, except for process-signup.php.  The coding does prevent a duplicate record from being created; however, the error message:  "email already taken" does not print.  Instead, the following error message prints when I added a new user with the same email as another user:  

Fatal error: Uncaught mysqli_sql_exception: Duplicate entry '[hal@mail.com](mailto:hal@mail.com)' for key 'email' in C:\xampp\htdocs\php-signup-login-main\process-signup.php:45 Stack trace: #0 C:\xampp\htdocs\php-signup-login-main\process-signup.php(45): mysqli_stmt->execute() https://github.com/daveh/php-signup-login/issues/1 {main} thrown in C:\xampp\htdocs\php-signup-login-main\process-signup.php on line 45

This is the code for http://localhost/php-signup-login-main/process-signup.php:

The coding that I submitted for process-signup.php, in my previous comment, did not preview as I expected.  Here are the actual screenshots for http://localhost/php-signup-login-main/process-signup.php:

![image](https://github.com/daveh/php-signup-login/assets/138462541/2b7b8444-a6f1-4f97-9240-0c3f3f751020)
![image](https://github.com/daveh/php-signup-login/assets/138462541/7b616e67-d654-4ed5-bbf1-5f81405563f8)
![image](https://github.com/daveh/php-signup-login/assets/138462541/779389b0-5d08-45e6-811f-ba4f5110de42)
![image](https://github.com/daveh/php-signup-login/assets/138462541/f0d2bc33-bc7d-4e08-bd68-7bb05176a8aa)

**Comment by daveh** [comment]
@techangela1 Try adding this line to the top of your script:

`mysqli_report(MYSQLI_REPORT_OFF);`

**Comment by techangela1** [comment]
Hello Dave,

You suggested that I put this line at the top of the script.  The page is:
php-signup.php

mysqli_report(MYSQLI_REPORT_OFF);

When I put it as the very first line (above the php opening tag, I got this
error:

*mysqli_report(MYSQLI_REPORT_OFF); Name is required*



When I put it after the php opening tag, I got this error:  *Name is
required*


Any suggestions?

**Comment by daveh** [comment]
@techangela1 That's the validation error you get when the form is submitted with no value for the name - try submitting the form with valid data
