### ISSUE TITLE
How to make same as email but now with name "already taken"

### ISSUE THREAD

**Issue by SWEz11** [daveh/php-signup-login#18]
Hello I want to ask how to make same as email but now with name "already taken" I tried but didn't work. 

```
<?php

$mysqli = require __DIR__ . "/database.php";

// Check if $_GET["name"] is set and not empty
$name = isset($_GET["name"]) ? trim($_GET["name"]) : "";

// Check if email is not empty after trimming
if (!empty($name)) {
    $escaped_name = $mysqli->real_escape_string($name);

    $sql = "SELECT * FROM user WHERE name = '$escaped_name'";
    
    $result = $mysqli->query($sql);

    if ($result !== false) {
        $is_available = $result->num_rows === 0;
        echo json_encode(["available" => $is_available]);
    } else {
        die("Error: " . $mysqli->error);
    }
} else {
    echo json_encode(["error" => "Invalid or empty email parameter"]);
}
?>
```

I tried like this but didn't work

Thank you!

**Comment by SWEz11** [comment]
And i make it in validation.js:
validation

>     .addField("#name", [
>         {
>             rule: "required"
>         },
>         {
>             rule: "name"
>         },
>         {
>             validator: (value) => () => {
>                 return fetch("validate-name.php?email=" + encodeURIComponent(value))
>                        .then(function(response) {
>                            return response.json();
>                        })
>                        .then(function(json) {
>                            return json.available;
>                        });
>             },
>             errorMessage: "Name already taken"
>         }
>     ])

But it won't work

**Comment by daveh** [comment]
In what way doesn't it work? Do you get any error messages? Try debugging the code by inserting debugging statements to print out the values of the variables at different stages

**Comment by SWEz11** [comment]
Hello daveh,

Thank you for response!

It seems like just the validate-name.php be skipped when the button be pressed in register window. No errors. Did I need connect the validate-name.php with process-signup or something like that? Or need write specific code for name checking? Thanks:)

**Comment by daveh** [comment]
In your JavaScript, you're passing the name value in the query string with an index of "email":

`return fetch("validate-name.php?email=" + encodeURIComponent(value))`

but then getting this on the server with an index of name: `$_GET["name"]`

Try changing them so they match, e.g. 

`return fetch("validate-name.php?name=" + encodeURIComponent(value))`

**Comment by SWEz11** [comment]
I already do it, but still didn't work

**Comment by daveh** [comment]
Check the browser console to see what JS requests are being made, and if there are any errors

**Comment by SWEz11** [comment]
That's I've got when I pressed signup button
![image](https://github.com/daveh/php-signup-login/assets/137026304/638a9f75-8786-4a5d-9256-221c9c9a9ae5) From console I've got nothing

**Comment by daveh** [comment]
From that it looks like the JavaScript validation isn't running when you submit the form. Check the code that attaches the validation to the form, it could be that.

**Comment by SWEz11** [comment]
It seem the validation is attached, but from now when I go to the signup.html page it show error in console: 
![image](https://github.com/daveh/php-signup-login/assets/137026304/3631367d-12ff-4231-ba0a-417b4c496428)
A somehow the code didn't change in website

This code from vs studio:
```
const validation = new JustValidate("#signup");

validation
    .addField("#name", [
        {
            rule: "required"
        },
        {
            rule: "name"
        },
        {
            validator: (value) => () => {
                return fetch("validate-name.php?name=" + encodeURIComponent(value))
                        .then(function(response) {
                        console.log("Server Response:", response);  // Add this line
                        return response.json();
                        })
                       .then(function(json) {
                           return json.available;
                       });
            },
            errorMessage: "Name already taken"
        }
    ])
    .addField("#email", [
        {
            rule: "required"
        },
        {
            rule: "email"
        },
        {
            validator: (value) => () => {
                return fetch("validate-email.php?email=" + encodeURIComponent(value))
                       .then(function(response) {
                           return response.json();
                       })
                       .then(function(json) {
                           return json.available;
                       });
            },
            errorMessage: "email already taken"
        }
    ])
    .addField("#password", [
        {
            rule: "required"
        },
        {
            rule: "password"
        }
    ])
    .addField("#password_confirmation", [
        {
            validator: (value, fields) => {
                return value === fields["#password"].elem.value;
            },
            errorMessage: "Passwords should match"
        }
    ])
    .onSuccess((event) => {
        document.getElementById("signup").submit();
    });
```

And what code I see in chrome:
```
const validation = new JustValidate("#signup");

validation
    .addField("#name", [
        {
            rule: "required"
        }
    ])
    .addField("#email", [
        {
            rule: "required"
        },
        {
            rule: "email"
        },
        {
            validator: (value) => () => {
                return fetch("validate-email.php?email=" + encodeURIComponent(value))
                       .then(function(response) {
                           return response.json();
                       })
                       .then(function(json) {
                           return json.available;
                       });
            },
            errorMessage: "email already taken"
        }
    ])
    .addField("#password", [
        {
            rule: "required"
        },
        {
            rule: "password"
        }
    ])
    .addField("#password_confirmation", [
        {
            validator: (value, fields) => {
                return value === fields["#password"].elem.value;
            },
            errorMessage: "Passwords should match"
        }
    ])
    .onSuccess((event) => {
        document.getElementById("signup").submit();
    });
```

But I don't know it make a sence.
But the error can be solution

**Comment by daveh** [comment]
If JustValidate is not defined, then it looks like that library isn't being loaded. Check the network console to see if there is an error when requesting that file, or make sure you're loading that file before your own one.

**Comment by SWEz11** [comment]
I added this line in signup.html: 
`<script src="https://unpkg.com/just-validate@2.4.0/dist/js/just-validate.min.js"></script>`
And now in network console show this: 
![image](https://github.com/daveh/php-signup-login/assets/137026304/fe8bd9fb-5f12-4690-ace8-07758a1e8225)

Now it seems the validation.js is working but show the just-validate.min.js been failed it when you pressed on the just-validate.min.js text it in next page show this: 
![image](https://github.com/daveh/php-signup-login/assets/137026304/72232e89-514e-410b-a1a7-d3f35629e8d3)
It can be the version problem but I don't know how to get normal link with normal version ( I get it from ChatGPT)

But when you enter already create name it still allow to signup

**Comment by daveh** [comment]
You can get it from [the official website](https://just-validate.dev/):

`<script src="https://unpkg.com/just-validate@latest/dist/just-validate.production.min.js"></script>`

**Comment by SWEz11** [comment]
Yea it work with js!
![image](https://github.com/daveh/php-signup-login/assets/137026304/3f4c5a77-0245-4956-b5be-f25fe34ff8e9)
But still allow to use already taken name
![image](https://github.com/daveh/php-signup-login/assets/137026304/c389c60e-17f2-4153-af1c-416df3b7887c)

**Comment by daveh** [comment]
Try debugging by seeing what value is being returned from the script that checks the email address and returns a value to the JavaScript

**Comment by SWEz11** [comment]
Now I tried in localhost Host and it seems the website signup.html see validation normally because in website Host it just validation look like this ` .addField("#name", [
        {
            rule: "required"
        }
    ])`

instead looking like this:
`    .addField("#name", [
        {
            rule: "required"
        },
        {
            rule: "name"
        },
        {
            validator: (value) => () => {
                return fetch("validate-name.php?name=" + encodeURIComponent(value))
                        .then(function(response) {
                        console.log("Server Response:", response);  // Add this line
                        return response.json();
                        })
                       .then(function(json) {
                           return json.available;
                       });
            },
            errorMessage: "Name already taken"
        }
    ])`


In local host I'm getting signup.html console error:
`Uncaught Error: Rule should be one of these types: required, email, minLength, maxLength, password, number, integer, maxNumber, minNumber, strongPassword, customRegexp, minFilesCount, maxFilesCount, files. Provided value: name
    at just-validate.production.min.js:1:18898
    at Array.forEach (<anonymous>)
    at Object.addField (just-validate.production.min.js:1:18676)
    at validation.js:4:6`

And I cant press signup button:
![image](https://github.com/daveh/php-signup-login/assets/137026304/c62cb356-6975-4d98-8a40-d965d0299593)
    
    validation.js 4 line: 
    ` .addField("#name", [`.
    
    PS: In both places (LocalHost , Website Host):
    Read the validate-name.php: because when I enter websitename.com/path/path2/validate-name.php?name=5353
    
    I'm getting this: 
    
![image](https://github.com/daveh/php-signup-login/assets/137026304/4abab580-b32b-4db4-9aed-643fc67baae3)

**Comment by daveh** [comment]
Perhaps the syntax has changed in a more recent version of JustValidate - the documentation is [here](https://just-validate.dev/).

**Comment by SWEz11** [comment]
It work:)! But small problem: How why when I press the signup button without writting email address in email area. It just say email already exits if I didn't not write anything
![image](https://github.com/daveh/php-signup-login/assets/137026304/e6a35697-47bb-45cd-a4f7-78c7932759d6)

**Comment by daveh** [comment]
Try debugging the script that checks the emails by running the PHP code directly with an empty string for the email address. You can run the PHP script directly by requesting it in the browser's address bar, passing the email in the query string. You can print out debugging statements to see what values the various statements in the PHP are returning, to see where the issue is.

**Comment by SWEz11** [comment]
### Thank you daveh for all your support:)!
